version: 2

builds:
  - main: .
    binary: aws-vpn-saml
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: binary

release:
  name_template: "aws-vpn-saml {{ .Tag }}"
